### PR TITLE
Osx arm64 (attempt 2)

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by croth1** [comment]
To my understanding we don't have qt for osx_arm64 available here in conda-forge (cc @isuruf for fact-checking). If you are fine having gnuplot without the qt backend, you should be able to build gnuplot by making the qt dependency conditional and changing this line to `--without-qt`.
https://github.com/conda-forge/gnuplot-feedstock/blob/ee36ca6c09284bac303e79199b25293e3a401fe7/recipe/build.sh#L11

**Comment by Tobias-Fischer** [comment]
Unfortunately it still fails as it's trying to execute an arm64 executable on the x86 host ..

**Comment by Tobias-Fischer** [comment]
@conda-forge/help-osx-arm64 do you have any suggestions on how to proceed?

**Comment by erykoff** [comment]
Ah, one of these annoying packages that builds something and then uses that as part of the build.  The only thing to do is to make a temporary build directory and build it natively, and also patch the makefile (or whatever) to use the native version within the build.  Prior art, for example, is https://github.com/conda-forge/emacs-feedstock/blob/master/recipe/build.sh#L18

**Comment by Tobias-Fischer** [comment]
Ah that's a shame. Unfortunately I won't be able to push this PR further - if someone wants to take it over, this would be great.

**Comment by Tobias-Fischer** [comment]
See #43

**Pull request closed without merging**
