### PR TITLE
add libgcc as runtime dependency

### PR DESCRIPTION
**Pull request by bgruening**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bgruening** [comment]
@croth1 @ocefpaf I tried to create a container out of this package but installing the recipe in a busybox container yields the following error. This is a general problem with conda-forge packages afaik, but it only occurs in this very special setting. Still ok to merge?

```
[Apr 23 09:28:46] STEP Run image [quay.io/biocontainers/gnuplot:5.2.2--hfb11a44_0] with command [[gnuplot -e "set terminal png"]]
[Apr 23 09:28:46] DEBU Creating container [step-cff456c681]
[Apr 23 09:28:46] DEBU Created container [defd335fcff8 step-cff456c681], starting it
[Apr 23 09:28:46] DEBU Container [defd335fcff8 step-cff456c681] started, waiting for completion
[Apr 23 09:28:46] SERR gnuplot: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
[Apr 23 09:28:47] ERRO Task processing failed: Unexpected exit code [127] of container [defd335fcff8 step-cff456c681], container preserved
```

**Comment by jakirkham** [comment]
FWIW we are moving to `defaults` compilers, which will automatically include things like `libgcc` at run time.

ref: https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#anaconda-compilers-and-conda-build-3

**Comment by bgruening** [comment]
@jakirkham for the time being - good to merge?

**Comment by jakirkham** [comment]
So this is far enough at the end of the dependency chain (only `octave` requires `gnuplot`) that it might be reasonable to just start using the new compilers here. We would need to rebuild `octave` with them as well, but that's not a big ask I don't think. @isuruf and @msarahan, what are your thoughts on this?

**Comment by msarahan** [comment]
worth a try on the new compilers if you are up for it.

**Pull request closed without merging**
